name: pygeoogc-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cytoolz
  - defusedxml
  - owslib
  - pyproj
  - requests
  - requests_cache
  - setuptools
  - shapely
  - simplejson

  - pytest
  - pytest-cov
  - pytest-xdist
  - flaky
