name: pygeoogc-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - setuptools
  - owslib
  - pyproj
  - shapely
  - orjson
  - simplejson
  - defusedxml
  - requests
  - aiohttp
  - chardet
  - aiodns
  - brotlipy
  - nest-asyncio
  - cytoolz
