name: pygeoogc-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiodns
  - aiohttp
  - aiosqlite
  - brotlipy
  - chardet
  - cytoolz
  - defusedxml
  - nest-asyncio
  - orjson
  - owslib
  - pyproj
  - requests
  - requests_cache
  - setuptools
  - shapely
  - simplejson

  - pytest
  - pytest-cov
  - pytest-xdist
  - flaky

  - pip
  - pip:
    - aiohttp-client-cache
